### ISSUE TITLE
IDDAv2 demand

### ISSUE THREAD

**Issue by zafirshi** [valeriopaolicelli/SegVPR#1]
Hi~  Thx for your excellent work！

I am very interested in your experimental results and want to use the dataset proposed in the paper - **iddav2**. Can you leave your email or other contact information? (I'm sorry I haven't found it for a long time)

Hope you have a nice day！

**Comment by valeriopaolicelli** [comment]
Hi, thanks for your interest! IDDAv2 will be released on https://idda-dataset.github.io/home/ within 2 weeks.
Don't worry, I'll comment here again when it will be available.

kind regards

**Comment by jsdd25** [comment]
@valeriopaolicelli Hello! Your work is very excellent. I want to use the dataset IDDAv2. Is the dataset open-sourced? Where can I download?

kind regards

**Comment by taveraantonio** [comment]
Hello @jsdd25. We are preparing the dataset to its release soon. It will be released before the 25/05, which is the date where the paper will be presented to the ICIAP 2021 conference. I will text to you as soon the dataset is available for download.

**Comment by taveraantonio** [comment]
@jsdd25 IDDA v2 dataset is now available for download. Send your download request here: https://idda-dataset.github.io/home/
