### ISSUE TITLE
How is Attention heatmaps drawn?

### ISSUE THREAD

**Issue by wpumain** [valeriopaolicelli/SegVPR#2]
How is Attention heatmaps drawn?
Can you provide the following source code?
Think you

**Comment by valeriopaolicelli** [comment]
Hello @wpumain, thanks for your question. 
Sorry for the late reply but I’m no longer supporting and monitoring this project.
Anyway, there is a function in this repository to extract and save the heatmaps.
Try to give a look here
https://github.com/valeriopaolicelli/SegVPR/blob/main/src/test_semseg.py#L37

Thanks

**Comment by wpumain** [comment]
Think you for your help!
