### ISSUE TITLE
About the Figure 4 in the AdAGeo - WACV2021 paper

### ISSUE THREAD

**Issue by MAX-OTW** [valeriopaolicelli/SegVPR#5]
Hello, @valeriopaolicelli ,I really appreciate for your work in AdAGeo - WACV2021.
The Figure 4:(Visualization of attention score maps）in the AdAGeo - WACV2021 paper looks good, currently I want to try to implement it but I failed. Is it convenient to provide the relevant implementation code?Of course, detailed guidance would be better.
I am always looking forward to your kind response.
Best regards.

**Comment by valeriopaolicelli** [comment]
Hello @MAX-OTW 
I wrote a comment for this issue in AdAGeo [repository](https://github.com/valeriopaolicelli/adageo-pytorch).
Please, check this: https://github.com/valeriopaolicelli/adageo-pytorch/issues/3
BR
Valerio
